// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mxxrlalioldhoawlctqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14eHJsYWxpb2xkaG9hd2xjdHFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMDcwMzgsImV4cCI6MjA2ODU4MzAzOH0.VCEf4giFtBbsRbFr5y4Aj8fgbed_Jyt8CC2li1Kuu8I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});